apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: w3w8gv7ff-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-1d1c33fd7d.8olc.p3.openshiftapps.com/rhtap/rhtap-qe-java-quarkus:e66ac19dae96d98f56cbc49ea17577b2dcbdc5c4@sha256:5497557205e082305859a96571f31153f705c5db7edb598c2bb626e67a133260
        name: container-image  
